name: Test
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
      matrix:
        erlang_version:
        - "22.3"
        - "23.1"
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v2
    - name: CONFIGURE OTP & ELIXIR
      uses: actions/setup-elixir@v1
      with:
        otp-version: ${{ matrix.erlang_version }}
        # https://github.com/elixir-lang/elixir/releases
        elixir-version: 1.10.4
    - name: MOUNT BAZEL CACHE
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        # use a version keyed cache, since we don't control the version of erlang/elixir within bazel yet
        key: bazel-${{ matrix.erlang_version }}
    - name: INSTALL BAZELISK
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
    - name: RUN TESTS
      run: |
        bazel test deps/rabbit_common:all
